# Generated by Django 5.2.1 on 2025-05-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/')),
                ('stock', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessory_type', models.CharField(max_length=100)),
                ('compatibility', models.TextField(help_text='Compatible equipment')),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='LEDProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/')),
                ('stock', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('led_type', models.CharField(max_length=100)),
                ('pixel_pitch', models.FloatField(help_text='Pixel pitch in mm')),
                ('brightness', models.IntegerField(help_text='Brightness in nits')),
                ('panel_size', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'LED Display',
                'verbose_name_plural': 'LED Displays',
            },
        ),
        migrations.CreateModel(
            name='LightingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/')),
                ('stock', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lighting_type', models.CharField(max_length=100)),
                ('wattage', models.IntegerField(help_text='Power consumption in watts')),
                ('beam_angle', models.CharField(max_length=100)),
                ('color_temperature', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Lighting Equipment',
                'verbose_name_plural': 'Lighting Equipment',
            },
        ),
        migrations.CreateModel(
            name='SoundProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/')),
                ('stock', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sound_type', models.CharField(max_length=100)),
                ('power_output', models.IntegerField(help_text='Power output in watts')),
                ('frequency_response', models.CharField(max_length=100)),
                ('connectivity', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Sound Equipment',
                'verbose_name_plural': 'Sound Equipment',
            },
        ),
        migrations.CreateModel(
            name='StageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/')),
                ('stock', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_type', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('max_load', models.FloatField(help_text='Maximum load capacity in kg')),
                ('material', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Stage Equipment',
                'verbose_name_plural': 'Stage Equipment',
            },
        ),
    ]
